# Generated by Django 5.2.5 on 2025-08-19 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_uri', models.URLField(blank=True, default='')),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
